apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brawl-draft-collector-data-v2
  namespace: brawl-draft
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
