#!/usr/bin/env bash
# Render the CRDs of a traefik Helm chart version into the file that k3s
# applies next to the chart. Renovate runs this when it bumps the chart in
# k3s.nix; CI re-runs it to check the committed file is current.
#
# Usage: traefik-crds.sh <chart-version> [output-file]
set -euo pipefail

version=$1
out=${2:-infra/nixos/hosts/k8s-server/traefik-crds.yaml}

crds=$(helm show crds traefik --repo https://traefik.github.io/charts --version "$version")

# Keep only CRDs: helm show crds prints whatever the chart's crds/ holds, and
# anything else would be applied with cluster-wide rights.
filtered=$(
  printf '%s\n' "$crds" | awk '
    # Documents holding only comments (license headers) are dropped.
    function flush() {
      if (body ~ /[^[:space:]]/) {
        if (doc !~ /(^|\n)kind: CustomResourceDefinition\n/) {
          print "traefik chart crds/ contains a non-CRD document" > "/dev/stderr"
          bad = 1
        } else {
          printf "---\n%s", doc
        }
      }
      doc = ""
      body = ""
    }
    /^---/ { flush(); next }
    { doc = doc $0 "\n" }
    !/^[[:space:]]*#/ { body = body $0 "\n" }
    END { flush(); exit bad }
  '
)

{
  echo "# Generated by .github/scripts/traefik-crds.sh from the traefik chart $version."
  echo "# Do not edit; Renovate regenerates it when it bumps the chart in k3s.nix."
  printf '%s\n' "$filtered"
} >"$out"
