zigbee2mqtt-secret: ENC[AES256_GCM,data:Xk1Zy2ipc5JExTE20X4w/G6RTgD8QdmNOPc0KTuvNvnTHbqnoNYZRsaa6PLPfIk4cdsXb+J4xFTxkZk6TQwFRa4nzo/uSdE3LUCjFHTixFVKrAE=,iv:UY4OgENfAoqOIH+/66zG/9mNyp87uTZKHx4jHrh6h8E=,tag:2dhGicw5JZActH9LnTQ3gQ==,type:str]
digitransit-api-key: ENC[AES256_GCM,data:KhRgB0l2UISWqFwfYNRtEsHcfES7PvqmG51phwv0UOw=,iv:n9xe7pJe5WbrudlN2TP0SYjp65edu1zuLk5xuCjOVng=,tag:z2jAT+yNiX+Tx8V84y53WA==,type:str]
mythos-wifi-qr-payload: ENC[AES256_GCM,data:DCnGhoT86oxUUe5wBLp/JrhWSnDwG0Swklf7gWzzuv0I7P492cxLCVoHo6wsM0g2,iv:ujUYNGhamligkGs5FHhnxilfTLqtllOimPgcM8jKyWU=,tag:C89pnOZnXkdOzzzlaiKEYQ==,type:str]
cloudflare-dns-api-token: ENC[AES256_GCM,data:HKRwrIQKE6scKYoeK4b+tdJ+hmwZ3+lUMoVs6dfQdQ8UOxgtXnd45cszDrpq3mZHxFQdKVs=,iv:ELhcDmLkDMaX3TdkK/HSDm7uc2ii34OFTbdFblfETdk=,tag:1AQ93/1JxXvE8Ef0SKPygw==,type:str]
router-deploy-ssh-key: ENC[AES256_GCM,data:N414XkzP9UN+HmNeI/TC8eFQ8JFgBo7273NwEwvGCpQNuG6YZzO2P5JVHaV7c+ASd38NQ18vlvhEMAWjDsDV51KZLrRjX0bqgKvm2fdahpe8Rupgzi2fR2tZOyrbI16lT7YkrDZVLHUetpOC8cU+51AnJR1bCgTXFGvB/1E4O65ZlY7ST0JMsYLwtQAqNZjeE3ZGrFiChRc7CoteOhBPu72lUl8d/CnWcWe92fLyFiRmJjiBHFVDFpmJEo5Uy8UotbMaXZu7gkGEguAF+xGPVej1kCspYuG8ifPzVUdyK02lt3XJkvrczazS+W0IORAZb9WiWLh7Gn2KJN95MDt2xrvk3iq9lfVJa2IvySWbwjA9uD/zFFE9qjOwxDmY5XjmIZGZwR9fFNsZZ3/Hj6GGREyaMXI50XXJuO++xV1TpSdkzKJx8F3y7c2fMXG4rwpKQ1wI4Gyu9LDqAN4B7wShyNSJBnztEClSzX5mywzkKoyHQ39JYAsfCdsoaot+jIeH05t7vkW8q/oMxmZ6D1uIK/utiPti2GGBv5BN,iv:DhliYXAWBz8JUX6bFXyGw2yOHuNYMifIbiEb9w6tWqY=,tag:perbBfgI115zl5nCfE2Ofw==,type:str]
github-ssh-key: ENC[AES256_GCM,data:nmzjKdNglqgQ1tohB7HZKaX8vTKnXBA3/HB7LBj+Bi3ALqlBaFoQggHDalGA/Qa4Z/GSThn/zkXzvgZce2PPPz2YST2MHyLvqo99TRqwpMF8h92o+IEktX0Gn1cqVd7vwXINv2sMkeGFnOgZjIb4DfjN5YGfqdQpfvEPd8lgeNcNXykXi+menbcnuCAbjisncYmnk9aMt3xcSA5jPxDu7m8T9ecSb8z48sqAgKBBHSpvW3ZtFpQOiIbhF6+6C+MGlsyTH/Eq/jFRSppL/BKHtAfPD/4KXEJm+jcK7Xl7WAT2T5AvAUBjxgyarLKlZJ+X4McGzZaxgMg287wlN7MY/gZA/aOlIocBiN6/n4IeoRczTFmyMH3MdGnPWzRhpPU0DNuHoDsfLTolw6DpQGe/RiUoiGpFl7JCqjHELzQg/3Xj++DPw6UIJkS+UnYebBsV2S1A5RIBI/j+Np00VBA0IHdfQuQ8MSV8UiuBdVknfOD+el3wCN+cyQ05xBweXTvvQSBKGk7YdOo6l/tEAqPSDVqEbd6zr2DWk99h9S1Hrq6Q/N8iwS4rW6KCPtDq1wKz,iv:r29zVuGOy6zDMFSx47JG/TrIdhRkaNLFfDzqQs96/9Y=,tag:2x9Nm00qLacvO8/3TekIZw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSW9XL2ZDSkFuWVRjaHBO
        Tm5QQkRSQWEyZU13YldGZ3o3UkZ1VnBHNzNBCmRDQlNuRjFOY1Z1aFVsN0xMK25D
        bGEyWENvZTBhUVFYWDNlaGtZTDlscncKLS0tIENmRHQvcDJ5YXQvUDBhU1dxTWUv
        cnpOa1NrQmk5WTRFaHVHSEQ4K1A2cXcKYWVtsizdWhCO+aozUH3mis79pxp6eNdX
        yH4fxgpX/W53BOPEOY5Zs8H15v22vPTsPXOF30ny97GFuUdeAeTkEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cg4jmsf6857fk9456uphmmqmjahvfv5hcxf75w7rsjay3p9kj40s0qg5tm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaDZad1FHaUpNVEo1SjFm
        YmZwVGcwMy91ZmRuUnRCcjd2OWU4UmJkaFFzCmFuSVFmVS8rS0ZyK2doTGUxdHhT
        TEtqZGp4L2ppb1JRU2xsUEJodTZDR1kKLS0tIG12aTVIK2gxalR3bmdlYzRSMWpS
        azFEWk94RjFMWWpGUkRhVXdCbHYwdXMK59Fd8J0prKj9Z7ik42/gQziJviC+3keA
        mnHbvPG5/t8oPO+hGtyYclsrdzuGQymaMbsLfllrxTT1b6PfWy/6xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nrzsajt427a8j2qed0c7cqpxw5k30vnhkl85gt54w66yvucm6vzqczrxx0
  lastmodified: "2026-09-06T07:43:14Z"
  mac: ENC[AES256_GCM,data:Qf3CozxGT+E+KZSeIeOKL0f7XjEKzAW8KeVALwYnxVVx4tTEoU4yhiFJRddNeU0aQUP+Vg86wC/BRAyNU5tvz8cOJ9stauUmh0bfK+KDMW0EmS0oNCh3Vs6X8cujVy6USKEYqMgA2SaiyxJfcaa5NKkjQuHTzh8CLkCKPIZuQ4w=,iv:U0iYJQ2SQI6dmWGqSbKy1I9JDIv8J8qNd5lgydmhTVs=,tag:1gb7ke7elwKnPM9x6rHMnQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
