apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: gatus
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
