apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.24.4
    helm:
      values: |
        tempo:
          metricsGenerator:
            enabled: true
            remoteWriteUrl: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal
          retention: 168h
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
        persistence:
          enabled: true
          storageClassName: local-path
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
